package uk.co.jmr.webforms.db.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * FieldTypes generated by hbm2java
 */
public class FieldTypes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String description;
	private Set<Fields> fieldses = new HashSet<Fields>(0);

	public FieldTypes() {

		super();
		this.id = -1;
	}

	public FieldTypes(int id, String name, String description) {

		this.id = id;
		this.name = name;
		this.description = description;
	}

	public FieldTypes(int id, String name, String description, Set<Fields> fieldses) {

		this.id = id;
		this.name = name;
		this.description = description;
		this.fieldses = fieldses;
	}

	public int getId() {

		return this.id;
	}

	public void setId(int id) {

		this.id = id;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	public Set<Fields> getFieldses() {

		return this.fieldses;
	}

	public void setFieldses(Set<Fields> fieldses) {

		this.fieldses = fieldses;
	}
}
