package uk.co.jmr.webforms.db.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * Fields generated by hbm2java
 */
public class Fields implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
	private FieldTypes fieldTypes;
	private Arrays arrays;
	private String name;
	private String description;
	private short attributes;
	private String validationJs;
	private Set<FormFieldMap> formFieldMaps = new HashSet<FormFieldMap>(0);

	public Fields() {

		super();
		this.id = -1L;
	}

	public Fields(long id, FieldTypes fieldTypes, String name, short attributes) {

		this.id = id;
		this.fieldTypes = fieldTypes;
		this.name = name;
		this.attributes = attributes;
	}

	public Fields(long id, FieldTypes fieldTypes, Arrays arrays, String name, String description, short attributes,
		String validationJs, Set<FormFieldMap> formFieldMaps) {

		this.id = id;
		this.fieldTypes = fieldTypes;
		this.arrays = arrays;
		this.name = name;
		this.description = description;
		this.attributes = attributes;
		this.validationJs = validationJs;
		this.formFieldMaps = formFieldMaps;
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {

		this.id = id;
	}

	public FieldTypes getFieldTypes() {

		return this.fieldTypes;
	}

	public void setFieldTypes(FieldTypes fieldTypes) {

		this.fieldTypes = fieldTypes;
	}

	public Arrays getArrays() {

		return this.arrays;
	}

	public void setArrays(Arrays arrays) {

		this.arrays = arrays;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	public short getAttributes() {

		return this.attributes;
	}

	public void setAttributes(short attributes) {

		this.attributes = attributes;
	}

	public String getValidationJs() {

		return this.validationJs;
	}

	public void setValidationJs(String validationJs) {

		this.validationJs = validationJs;
	}

	public Set<FormFieldMap> getFormFieldMaps() {

		return this.formFieldMaps;
	}

	public void setFormFieldMaps(Set<FormFieldMap> formFieldMaps) {

		this.formFieldMaps = formFieldMaps;
	}
}
