package uk.co.jmr.webforms.db.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * FormDefs generated by hbm2java
 */
public class FormDefs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
	private String name;
	private String description;
	private char active;
	private String handlerClass;
	private Set<Forms> formses = new HashSet<Forms>(0);

	public FormDefs() {

		super();
		this.id = -1L;
	}

	public FormDefs(long id, String name, char active) {

		this.id = id;
		this.name = name;
		this.active = active;
	}

	public FormDefs(long id, String name, String description, char active, String handlerClass, Set<Forms> formses) {

		this.id = id;
		this.name = name;
		this.description = description;
		this.active = active;
		this.handlerClass = handlerClass;
		this.formses = formses;
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {

		this.id = id;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	public char getActive() {

		return this.active;
	}

	public void setActive(char active) {

		this.active = active;
	}

	public String getHandlerClass() {

		return this.handlerClass;
	}

	public void setHandlerClass(String handlerClass) {

		this.handlerClass = handlerClass;
	}

	public Set<Forms> getFormses() {

		return this.formses;
	}

	public void setFormses(Set<Forms> formses) {

		this.formses = formses;
	}
}
