package uk.co.jmr.webforms.db.pojo;

import java.util.Date;

/**
 * FormData generated by hbm2java
 */
public class FormData implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private long id;
	private UserForms userForms;
	private HtmlFormDef htmlFormDef;
	private int vindex;
	private String textValue;
	private Date dateValue;
	private Long intValue;
	private Double numberValue;

	public FormData() {

		super();
		this.id = -1L;
	}

	public FormData(long id, UserForms userForms, HtmlFormDef htmlFormDef) {

		this.id = id;
		this.userForms = userForms;
		this.htmlFormDef = htmlFormDef;
	}

	public FormData(long id, UserForms userForms, HtmlFormDef htmlFormDef, int vindex, String textValue, Date dateValue,
		Long intValue, Double numberValue) {

		this.id = id;
		this.userForms = userForms;
		this.htmlFormDef = htmlFormDef;
		this.vindex = vindex;
		this.textValue = textValue;
		this.dateValue = dateValue;
		this.intValue = intValue;
		this.numberValue = numberValue;
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {

		this.id = id;
	}

	public UserForms getUserForms() {

		return this.userForms;
	}

	public void setUserForms(UserForms userForms) {

		this.userForms = userForms;
	}

	public HtmlFormDef getHtmlFormDef() {

		return this.htmlFormDef;
	}

	public void setHtmlFormDef(HtmlFormDef htmlFormDef) {

		this.htmlFormDef = htmlFormDef;
	}

	public int getVindex() {

		return this.vindex;
	}

	public void setVindex(int vindex) {

		this.vindex = vindex;
	}

	public String getTextValue() {

		return this.textValue;
	}

	public void setTextValue(String textValue) {

		this.textValue = textValue;
	}

	public Date getDateValue() {

		return this.dateValue;
	}

	public void setDateValue(Date dateValue) {

		this.dateValue = dateValue;
	}

	public Long getIntValue() {

		return this.intValue;
	}

	public void setIntValue(Long intValue) {

		this.intValue = intValue;
	}

	public Double getNumberValue() {

		return this.numberValue;
	}

	public void setNumberValue(Double numberValue) {

		this.numberValue = numberValue;
	}
}
