package uk.co.jmr.webforms.db.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.ardhika.wfar.WfModel;

/**
 * Forms generated by hbm2java
 */
public class Forms implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
	private int version;
	private FormDefs formDefs;
	private String name;
	private String description;
	private Character status;
	private String handCodedPath;
	private Date dateStart;
	private Date dateEnd;
	private String handlerClass;
	private Set<HtmlFormDef> htmlFormDefs = new HashSet<HtmlFormDef>(0);
	private Set<FormFieldMap> formFieldMapsForSubformId = new HashSet<FormFieldMap>(0);
	private Set<UserForms> userFormses = new HashSet<UserForms>(0);
	private Set<FormFieldMap> formFieldMapsForFormId = new HashSet<FormFieldMap>(0);

	private Set<WfModel> models = new HashSet<WfModel>();

	public Forms() {

		super();
		this.id = -1L;
	}

	public Forms(long id, String name, Date dateStart) {

		this.id = id;
		this.name = name;
		this.dateStart = dateStart;
	}

	public Forms(long id, FormDefs formDefs, String name, String description, Character status, String handCodedPath,
		Date dateStart, Date dateEnd, String handlerClass, Set<HtmlFormDef> htmlFormDefs,
		Set<FormFieldMap> formFieldMapsForSubformId, Set<UserForms> userFormses, Set<FormFieldMap> formFieldMapsForFormId) {

		this.id = id;
		this.formDefs = formDefs;
		this.name = name;
		this.description = description;
		this.status = status;
		this.handCodedPath = handCodedPath;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.handlerClass = handlerClass;
		this.htmlFormDefs = htmlFormDefs;
		this.formFieldMapsForSubformId = formFieldMapsForSubformId;
		this.userFormses = userFormses;
		this.formFieldMapsForFormId = formFieldMapsForFormId;
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {

		this.id = id;
	}

	public int getVersion() {

		return this.version;
	}

	public void setVersion(int version) {

		this.version = version;
	}

	public FormDefs getFormDefs() {

		return this.formDefs;
	}

	public void setFormDefs(FormDefs formDefs) {

		this.formDefs = formDefs;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getDescription() {

		return this.description;
	}

	public void setDescription(String description) {

		this.description = description;
	}

	public Character getStatus() {

		return this.status;
	}

	public void setStatus(Character status) {

		this.status = status;
	}

	public Date getDateStart() {

		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {

		this.dateStart = dateStart;
	}

	public Date getDateEnd() {

		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {

		this.dateEnd = dateEnd;
	}

	public String getHandlerClass() {

		return this.handlerClass;
	}

	public void setHandlerClass(String handlerClass) {

		this.handlerClass = handlerClass;
	}

	public Set<HtmlFormDef> getHtmlFormDefs() {

		return this.htmlFormDefs;
	}

	public void setHtmlFormDefs(Set<HtmlFormDef> htmlFormDefs) {

		this.htmlFormDefs = htmlFormDefs;
	}

	public Set<FormFieldMap> getFormFieldMapsForSubformId() {

		return this.formFieldMapsForSubformId;
	}

	public void setFormFieldMapsForSubformId(Set<FormFieldMap> formFieldMapsForSubformId) {

		this.formFieldMapsForSubformId = formFieldMapsForSubformId;
	}

	public Set<UserForms> getUserFormses() {

		return this.userFormses;
	}

	public void setUserFormses(Set<UserForms> userFormses) {

		this.userFormses = userFormses;
	}

	public Set<FormFieldMap> getFormFieldMapsForFormId() {

		return this.formFieldMapsForFormId;
	}

	public void setFormFieldMapsForFormId(Set<FormFieldMap> formFieldMapsForFormId) {

		this.formFieldMapsForFormId = formFieldMapsForFormId;
	}

	public String getHandCodedPath() {

		return handCodedPath;
	}

	public void setHandCodedPath(String handCodedPath) {

		this.handCodedPath = handCodedPath;
	}

	public Set<WfModel> getModels() {

		return models;
	}

	public void setModels(Set<WfModel> models) {

		this.models = models;
	}

}
