package uk.co.jmr.webforms.db.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * HtmlFormDef generated by hbm2java
 */
public class HtmlFormDef implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private long id;
	private Forms forms;
	private FormFieldMap formFieldMap;
	private String name;
	private int rank;
	private Set<FormData> formDatas = new HashSet<FormData>(0);

	public HtmlFormDef() {

		super();
		this.id = -1L;
	}

	public HtmlFormDef(long id, Forms forms, FormFieldMap formFieldMap, String name, int rank) {

		this.id = id;
		this.forms = forms;
		this.formFieldMap = formFieldMap;
		this.name = name;
		this.rank = rank;
	}

	public HtmlFormDef(long id, Forms forms, FormFieldMap formFieldMap, String name, int rank, Set<FormData> formDatas) {

		this.id = id;
		this.forms = forms;
		this.formFieldMap = formFieldMap;
		this.name = name;
		this.rank = rank;
		this.formDatas = formDatas;
	}

	public long getId() {

		return this.id;
	}

	public void setId(long id) {

		this.id = id;
	}

	public Forms getForms() {

		return this.forms;
	}

	public void setForms(Forms forms) {

		this.forms = forms;
	}

	public FormFieldMap getFormFieldMap() {

		return this.formFieldMap;
	}

	public void setFormFieldMap(FormFieldMap formFieldMap) {

		this.formFieldMap = formFieldMap;
	}

	public String getName() {

		return this.name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public int getRank() {

		return this.rank;
	}

	public void setRank(int rank) {

		this.rank = rank;
	}

	public Set<FormData> getFormDatas() {

		return this.formDatas;
	}

	public void setFormDatas(Set<FormData> formDatas) {

		this.formDatas = formDatas;
	}
}
