<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Form</title>



	
<link href='http://fonts.googleapis.com/css?family=Roboto:300,400,700,100' rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href="../resources/style/wizart/style.vali.css" />
<link rel="stylesheet" type="text/css" href="../resources/style/wizart/style.css" />

<link rel="stylesheet" type="text/css" href="../resources/style/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="../resources/style/demo_table_jui.css" />



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src='../resources/js/jquery.dataTables.min.js'
	type="text/javascript"></script>

<script>
	$(document).ready(function() {

		/* 	$('#historyTable').dataTable().rowGrouping({ iGroupingColumnIndex: 2,
				sGroupBy: "letter",
				bHideGroupingColumn: true }); */

		$("#formTableVal").dataTable({
			"bJQueryUI" : true,
			"sPaginationType" : "full_numbers",
			"bFilter" : true,
			"sScrollX": "100%",	
			/*  "sDom": 'T<"clear">lfrtip',
			 "oTableTools": {
		         "aButtons": [
		             {
		                 "sExtends": "print",
		                 "sButtonText": "",
		                 "sMessage": "Generated by Document Portal"
		             }
		         ]
		     }, */
			"iDisplayLength" : 100,
			"aaSorting" : [],
			"aoColumns" : [ {
				"bSortable" : false
			}, {
				"bSortable" : false
			}, {
				"bSortable" : false
			}, {
				"bSortable" : false
			}, {
				"bSortable" : false
			} ]
		});

	});
function csvDownloadFormClicked(){
	//alert("clicked");
	var oTable = $('#formTableVal').dataTable();
	var csv_value = oTable.fnGetData();
	alert(csv_value+""+oTable);
	$("#csv1_text").val(csv_value);
	$("#csvDownloadForm").attr("action", "csvForm");
	$("#csvDownloadForm").submit(); 
	}
</script>
</head>
<body>
	<div class="main">
		<div class="spacer">
		<!-- <div class="logo"></div>
			<div class="h12"></div> -->
			<div class="bor" >
			<div id="topForm">
				<div class="my-document complete box-content">
				<span class="float-left grid-box-header top3">Form >> ${formName}
				</span>
				</div>
				</div>
				<div id="dt_example" >
					<div id="stepListForm" >
						<table 
							class='display' id="formTableVal">
							<c:forEach var="i" items="${datas}">
							<thead>
								<tr>
								<c:forEach var="j" items="${i.key}">
									<th>${j}</th>
									</c:forEach>	
								</tr>
							</thead>
							<tbody>
								<%--  <c:forEach var="i" items="${histories}">
					 	<tr> <td>${i.actionDate}</td><td>${i.taskName}</td><td>${i.performedUser}</td><td>${i.action}</td></tr>
					 </c:forEach> --%>
								
									<%-- <tr>
									
										<td></td>
									
									</tr> --%>
									<tr style="display: none;">
									<c:forEach var="l" items="${i.key}">
										<td>${l}</td>
										</c:forEach>
										
									</tr>
									
									<tr>
									<c:forEach var="k" items="${i.value}">
										<td>${k}</td>
										</c:forEach>
										
									</tr>
								
							</tbody>
							</c:forEach>
						</table>
					</div>
				</div>
				<div align="center" class="divCenter">
					<form method="post" id="csvDownloadForm" name="csvDownloadFrm">
					<input type="hidden" name="csv1_text" value="" id="csv1_text" />
					<input type="hidden" name="userFormId" value="${userFormId }" id="userFormId" />
					<input type="button" id="btnCsvDownload" class="butn" value="Download"
					onClick="csvDownloadFormClicked();">
					</form>
				</div>
			</div>
		</div>
	</div>
</body>
</html>